### ISSUE TITLE
collectd plugin's type_instance missing problem

### ISSUE THREAD

**Issue by thyun** [elastic/logstash#2014]
When collectd uses df and memory plugin at the same time, sometimes logstash generates type_instance missing data .
Here is the problem output, look at the first line type_instance is missing:

{"@version":"1","@timestamp":"2014-09-04T07:20:42.143Z","host":"my-host","plugin":"memory","collectd_type":"memory","value":6250332160.0}
{"@version":"1","@timestamp":"2014-09-04T07:20:42.143Z","host":"my-host","plugin":"memory","collectd_type":"memory","type_instance":"buffered","value":55103488.0}
{"@version":"1","@timestamp":"2014-09-04T07:20:42.143Z","host":"my-host","plugin":"memory","collectd_type":"memory","type_instance":"cached","value":1283186688.0}
{"@version":"1","@timestamp":"2014-09-04T07:20:42.143Z","host":"my-host","plugin":"memory","collectd_type":"memory","type_instance":"free","value":665567232.0}

I fixed this problem and reporting now.
I used collectd 5.4.1 and logstash 1.4.2.
- Reason

The problem happens when you use df and memory plugin at the same time. 
Here's problem scenario.
Assuming collectd sets the following df and memory data sequentially in one UDP packet.

{"@version":"1","@timestamp":"2014-10-31T06:04:08.371Z","host":"example","type_instance":"used","plugin":"df","plugin_instance":"root","collectd_type":"df_complex","value":5076176896.0}

{"@version":"1","@timestamp":"2014-10-31T06:04:08.371Z","host":"example","type_instance":"used","plugin":"memory","collectd_type":"memory","value":7530356736.0}

collectd UDP protocol do not set the same data if it set it previously in a UDP packet (maybe to minimize packet size)
So, because collectd set "type_instance" as "used" in df data, it do not set "type_instance" again in memory data. (See protocol spec: https://collectd.org/wiki/index.php/Binary_protocol)

But logstash collectd plugin reset "type_instance" as blank when new "plugin" data comes in.
- How to fix the problem

I fixed lib/logstash/inputs/collectd.rb. 
I found the following 2 lines and fixed them.

From:
411 line: @collectd.delete(k) if !['host', '@timestamp'].include?(k)
417 line: @collectd.delete(k) if !['host', '@timestamp', 'plugin', 'plugin_instance'].include?(k)

To:
411 line: @collectd.delete(k) if !['host', '@timestamp', 'type_instance'].include?(k)
417 line: @collectd.delete(k) if !['host', '@timestamp', 'plugin', 'plugin_instance', 'type_instance'].include?(k)

And the problem disappeared.

See also: https://stackoverflow.com/questions/25659970/collectd-randomly-missing-type-instance-field/26730158#26730158

**Comment by iivarih** [comment]
I'm getting collectd's df and memory events without type_instance using udp input and collectd codec. Didn't notice this using only one machine running collectd. Now I have five machines running collectd and I get a lot of events without type_instance. (Logstash 1.4.2, collectd 5.4.1)

**Comment by untergeek** [comment]
Please do not use the collectd plugin, which is deprecated. These errors have already been corrected in the collectd codec.

**Comment by iivarih** [comment]
I'm using the collectd codec ;)

**Comment by iivarih** [comment]
I was able reproduce this with only one server running collectd. It seems that adding 'type_instance' also to 'PLUGIN_TYPE_FIELDS' fixes the problem but that might cause some consequences.

**Comment by oli-g** [comment]
@untergeek I'm still experiencing this with Collectd 5.5.0-1 and Logstash 1.5.5. Most of the events don't have the `type_instance` field. I'm using UDP input and collectd codec.

```
input {
  udp {
    port => 5001
    buffer_size => 1452
    codec => collectd { }
    type => collectd 
  }
}
```

```
LoadPlugin cpu
LoadPlugin df
LoadPlugin disk
LoadPlugin interface
LoadPlugin load
<LoadPlugin memory>
    Interval 10
</LoadPlugin>
LoadPlugin network
LoadPlugin rrdtool
LoadPlugin swap
LoadPlugin uptime

<Plugin df>
    Device "/dev/xvda1"
    MountPoint "/"
    FSType "ext4"
    ValuesAbsolute false
    ValuesPercentage true
</Plugin>﻿

<Plugin network>
    Server "logstash" "5001"
</Plugin>
```

What's the fix for this issue? I cannot grasp it from this discussion.
Thank you.

**Comment by untergeek** [comment]
@oli-g The most recent version of the plugin should have these fixes (it's at 2.0.4 right now).  You should update the plugin for these changes, which can be as simple as:

```
bin/plugin update logstash-codec-collectd
```

I would advise installing the most recent versions of Logstash, however.  There are performance improvements and the latest plugins are bundled with them.  We're about to release Logstash version 2.3.0.
