### ISSUE TITLE
logstash crash because of invalid @timestamp

### ISSUE THREAD

**Issue by christofhaerens** [elastic/logstash#3881]
Hi,

Running logstash 1.5.4 (from rpm 1.5.4-1) and logstash keeps crashing with the following error.

NoMethodError: undefined method `tv_sec' for "07/sep/2015:07:50:54 UTC":String

I know the @timestamp is wrongly constructed (it's shipped from tomcat who writes jason output via logstash forwarder). The format will be corrected in our tomcat logging config. But until it's fixed the logstash keeps crashing which is quite annoying. 
See also issue #1434. Isn't it possible to log a _timestamp_failure and then just continue with the rest of the events instead of crashing?

**Comment by markwalkom** [comment]
Can you provide your config as well as some sample data for this?

**Comment by christofhaerens** [comment]
Hi,

The logstash config on the server:
input { 
  lumberjack {
    port => 6782
    ssl_certificate => "/test_cert.pem"
    ssl_key => "/test_key.pem"
    type => "lumberjack"
  }
}
filter {
  if [type] == "tomcat-lsf" {
    json {
      source => 'message'
      add_tag => [ "tomcat", "dated", "lsf", "ls-<%= @_host %>" ]
    }
  }
}
output {
  elasticsearch {
    cluster => "our_cluster"
  }
}

The conf of the lumberjack:
{
  "network": {
    "servers": [ "ls1:6782", "ls2:6782" ],
    "ssl certificate": "",
    "ssl ca": "/ca.pem",
    "ssl key": "",
    "timeout": 15
  },
  "files": [
      "paths": [ "/var/log/tomcat/mlc/mlbConsulent.json.log" ],
      "fields": { "osfamily": "Suse", "type": "tomcat-lsf" }
    }
  ]
}


output in logstash.err:
NoMethodError: undefined method `tv_sec' for "07/sep/2015:08:24:43 UTC":String
       evaluate at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/string_interpolation.rb:135
       evaluate at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/string_interpolation.rb:80
        collect at org/jruby/RubyArray.java:2407
       evaluate at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/string_interpolation.rb:80
       evaluate at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/string_interpolation.rb:27
        sprintf at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/event.rb:222
        receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:522
         handle at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/outputs/base.rb:88
    output_func at (eval):497
   outputworker at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:244
  start_outputs at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:166


the output logstash.log:
{:timestamp=>"2015-09-07T10:36:45.329000+0200", :message=>"Trouble parsing json", :source=>"message", :raw=>"volgend contact voor dossier met ikl : 11449760", :exception=>#<LogStash::TimestampParserError: invalid timestamp string "07/sep/2015:08:24:43 UTC", error=java.lang.IllegalArgumentException: Invalid format: "07/sep/2015:08:24:43 UTC" is malformed at "/sep/2015:08:24:43 UTC">, :level=>:warn}

The entry from the tomcat log:
{"@timestamp":"07/sep/2015:08:24:43 UTC","level":"DEBUG","logger":"app.smp.ContactenController","message":"volgend contact voor dossier met ikl : 11449760"}


The strange thing tough is when I debug it via the stdin input (see conf below), it gives a json parse failure but it doesn't crash

the debug config:
input {
  stdin {
    type => "stdin-test"
  }
}
filter {
  if [type] == "stdin-test" {
    json {
      source => 'message'
      add_tag => [ "passed" ]
    }
  }
}
output {
  stdout {
    codec => "rubydebug"
  }
}

**Comment by jsvd** [comment]
@christofhaerens my suggestion here would be to use the `:target` option in the json filter to load the json message to a particular field in the logstash event instead of the root of the event. This way it won't overwrite the `@timestamp` field and break the event.

**Comment by jsvd** [comment]
Actually, It's strange how it's possible to get that string into @timestamp that way...doing some tests with logstash 1.5.4:

Using the json filter:
```
% echo '{"@timestamp": "07/sep/2015:07:50:54 UTC" }}' | bin/logstash -e 'input { stdin { } } filter { json { source => "message"} } output { stdout { codec => rubydebug } }'
Logstash startup completed
Trouble parsing json {:source=>"message", :raw=>"{\"@timestamp\": \"07/sep/2015:07:50:54 UTC\" }}", :exception=>#<LogStash::TimestampParserError: invalid timestamp string "07/sep/2015:07:50:54 UTC", error=java.lang.IllegalArgumentException: Invalid format: "07/sep/2015:07:50:54 UTC" is malformed at "/sep/2015:07:50:54 UTC">, :level=>:warn}
{
       "message" => "{\"@timestamp\": \"07/sep/2015:07:50:54 UTC\" }}",
      "@version" => "1",
    "@timestamp" => "07/sep/2015:07:50:54 UTC",
          "host" => "Joaos-MBP.lan",
          "tags" => [
        [0] "_jsonparsefailure"
    ]
}
Logstash shutdown completed
```

Using json codec:

```
% echo '{"@timestamp": "07/sep/2015:07:50:54 UTC" }}' | bin/logstash -e 'input { stdin { codec => json } } filter { } output { stdout { codec => rubydebug } }'
Logstash startup completed
Error parsing @timestamp string, setting current time to @timestamp, original in _@timestamp field {:value=>"\"07/sep/2015:07:50:54 UTC\"", :exception=>"invalid timestamp string \"07/sep/2015:07:50:54 UTC\", error=java.lang.IllegalArgumentException: Invalid format: \"07/sep/2015:07:50:54 UTC\" is malformed at \"/sep/2015:07:50:54 UTC\"", :level=>:warn}
{
     "@timestamp" => "2015-09-07T16:49:45.823Z",
       "@version" => "1",
           "tags" => [
        [0] "_timestampparsefailure"
    ],
    "_@timestamp" => "07/sep/2015:07:50:54 UTC",
           "host" => "Joaos-MBP.lan"
}
Logstash shutdown completed
```

So clearly the json filter is misbehaving here: it actually prints out an error trying to parse the date, still overwrites @timestamp, which doesn't happen in the json codec.

**Comment by jsvd** [comment]
@christofhaerens another option is to only process events without _jsonparsefailure in the output section:

```
output {
  if "_jsonparsefailure" not in [tags] {
      ...
  }
}
```

**Comment by christofhaerens** [comment]
Thxfs for the feedback.
The idea of passing the @timestamp directly in the tomcat json is that we don't have to apply the date filter in the logstash anymore.

And I can't activate the json codec on the lumberjack input because also plain messages are coming in that way. The date pattern is now adjusted so the logstash does'nt crash anymore, but seemed important enough to share this unlike behaviour so it can maybe fixed in a future version.

**Comment by jsvd** [comment]
@christofhaerens indeed. still not sure what the right behaviour should be when receiving a document with an incorrect @timestamp field. 

A failed parse will always add the `_jsonparsefailure` tag to the event so that event needs to be excluded from the rest of the pipeline as the event is pretty much useless.

**Comment by seang-es** [comment]
Have tested this against Logstash 2.1.1, and the event is tagged as _jsonparsefailure but LS does not crash.

**Comment by jordansissel** [comment]
@seang-es thanks for testing! I think we can close this.

If this issue still exists for someone, we can reopen.
