### ISSUE TITLE
Enormous amount of logstash processes open consuming lots of memory

### ISSUE THREAD

**Issue by javifr** [elastic/logstash#3958]
Hi, 

I have Logstash 1.5.0.rc2 running in Ubuntu 14.04.1 LTS.

My problem is that logstash even not processing anything, in a idle status, is opening a lot of huge memory consuming processes , until consuming almost all the memory in my production machine.

Here you can see the output of an htop command:
![captura de pantalla 2015-09-23 a las 17 24 01](https://cloud.githubusercontent.com/assets/353755/10049805/7df2a690-6219-11e5-93c0-cf344e02f647.png)

Does anyone could help me to avoid this thing?

Regards!

**Comment by ph** [comment]
Any details about the configuration? Can you attach a jstack <PID> dump to this issue?

**Comment by ph** [comment]
1.5.0rc2 is pretty old, we have fixed a fews major issue between that.

**Comment by javifr** [comment]
Thanks for the quick answer!
Could you point me to some resource explaining how to update from 1.5.0 rc2 to the current version?

**Comment by ph** [comment]
@javifr I presume you are using ubuntu package so it should be a matter of using apt, use the same config.

**Comment by javifr** [comment]
Thanks a lot. I upgraded logstash and I've got my system running again with the latest logstash release.

The memory usage is much lower than before, still don't understand why you can see on the output of top that much logstash processes:

![captura de pantalla 2015-09-23 a las 18 00 10](https://cloud.githubusercontent.com/assets/353755/10050516/0ec2e9fc-621d-11e5-887a-2e3e342b8175.png)

**Comment by ph** [comment]
@javifr If you can share the config, I would in better way to explain what could use that much resources.

**Comment by ph** [comment]
@javifr Wait, I though you only had one logstash process. Do you have something that restart it?

**Comment by jordansissel** [comment]
> is opening a lot of huge memory consuming processes , until consuming almost all the memory in my production machine

This is a common misunderstanding when looking at java processes, and the tools we have for inspecting systems don't make it very obvious. Java has many threads for its own maintenance tasks (memory management, etc), and Logstash uses threads as well for higher performance and other reasons.

I believe what you are seeing is just threads, not "processes" in the typical sense. Given that the pids are very close together and the memory usage reported is exactly the same for all logstash 'processes', I am very confident that you are simply looking at htop's output with thread display enabled, and that these 'java' processes are actually just all threads for one logstash process. Logstash will have many threads, and this is not necessarily cause for alarm.

Hope this helps :)

**Comment by ph** [comment]
gotcha Thx @jordansissel

**Comment by ph** [comment]
A bit more info @javifr http://unix.stackexchange.com/questions/10362/why-does-htop-show-more-process-than-ps

**Comment by javifr** [comment]
@jordansissel thank you so much for the great explanation!
@ph thank you also for the link resources.

My machine for the moment is running fine, so what I think really did the trick was updating logstash everything. Now the system seems to be stable at 500MB of memory consuming.

**Comment by ph** [comment]
thanks @javifr I'll close this issue!
