### ISSUE TITLE
Logstash 5.0.0-alpha4 - Error while installing plugins

### ISSUE THREAD

**Issue by ceeeekay** [elastic/logstash#5581]
Fresh install of LS 5 .0.0 alpha 4.

Trying to install any plugins results in an install error and a retry loop.

This initially occurred while trying to install a local .gem, however packaged plugins also produce the error.

>`# /usr/share/logstash/bin/logstash-plugin install logstash-filter-anonymize`
Validating logstash-filter-anonymize
Installing logstash-filter-anonymize
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.0.0.pre.alpha4), and Bundler cannot continue.
Make sure that gem install `logstash-core-event-java -v '5.0.0.pre.alpha4'` succeeds before bundling.

Ubuntu 14.04 amd64
Logstash 1:5.0.0~alpha4-1
openjdk-8-jre-headless 8u91-b14-0ubuntu4~14.04

**Comment by ceeeekay** [comment]
More info: I can reproduce this on some boxes, but not others, with the same OS and Java versions.

Still looking into why this may be happening.

**Comment by purbon** [comment]
thanks for your report @ceeeekay , I'm wondering what are the exact details that might make this happen as we routinely test with several operating systems our components.

Can you run this same command in the machines that show this behaviour with DEBUG=1? this will tell the system to output more information out.

**Comment by ceeeekay** [comment]
Hi @purbon 

Output is at https://gist.github.com/ceeeekay/bc0cff92fb0b8590a50708eff1cdf6d6

**Comment by purbon** [comment]
@ceeeekay I wonder if you actually updated this box or install it from scratch? the error shown is related to ruby-maven, what makes me believe there might be something fishy there.

**Comment by jsvd** [comment]
@ceeeekay can you also post your current Gemfile? thanks

**Comment by ceeeekay** [comment]
@purbon it was originally upgraded from 5.0.0-alpha3, but after the error occurred I purged the package and manually rm'ed /usr/share/logstash and /opt/logstash, before reinstalling the .deb for 5.0.0-alpha4 and trying again.

@jsvd https://gist.github.com/ceeeekay/e18352ff11f8d5ca0726f6765d5b21a0

**Comment by jsvd** [comment]
@mkristian sorry to ping you again on this, any idea on why the ruby dsl isn't being loaded? it's asking for the [deps.lst](https://gist.github.com/ceeeekay/bc0cff92fb0b8590a50708eff1cdf6d6#file-plugin-manager-output-txt-L212) file, but I don't think we ever had it in the package (looking at 5.0.0-alpha3 and 2.3.3)

**Comment by mkristian** [comment]
@jsvd the error message is misleading as it is not this missing file, the problem is probably that java can not access maven central using default ssl connection. maven does not use the ruby DSL which is the first thing it tries to install. if this fails it fails silently within maven and continues with regular maven, this fails and jar-dependencies just can not find this missing file. I will improve the error message here in the next release of jar-dependencies but the actual issue more likely on the missing certificate on the jdk installation (which was the case before with such error messages)

**Comment by mkristian** [comment]
FYI @jsvd ping my anytime :)

**Comment by jsvd** [comment]
I see, we fixed this in [another other ticket](https://github.com/elastic/logstash/issues/5325#issuecomment-220607374) with `sudo update-ca-certificates -f`
@ceeeekay can you check if this works for you?

**Comment by ceeeekay** [comment]
@jsvd I can confirm `sudo update-ca-certificates -f` resolves the issue for me.

Thanks everyone for looking into this :)

**Comment by purbon** [comment]
good finding @jsvd with the update-ca-certificates for ubuntu-1404 .... and happy tou @ceeeekay fix your issue.

closing this issue for now and opening a new one to deal on how to make this `update-ca-certificates` for documetation whise.

**Comment by ceeeekay** [comment]
@purbon just one more thing - is this considered a pre-existing issue or does it qualify for the pioneer program? I'm trying to collect as many as I can ;)

**Comment by vilure** [comment]
sudo update-ca-certificates -f doesn't resolve for ubuntu 16.04

**Comment by mkristian** [comment]
@vilure which jdk (debian package from which repo) are you using ?

if you install it can you prepend `JARS_DEBUG=true` and in case this really gives error output then please add the output as gist - thanx

**Comment by vilure** [comment]
@mkristian 
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000faa00000, 75497472, 0) failed; error='Cannot allocate memory' (errno=12)
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.0.0.pre.alpha4), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0.pre.alpha4'` succeeds before bundling.

openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

and sorry i ran sudo JARS_DEBUG=true /usr/share/logstash/bin/logstash-plugin install logstash-patterns-core
i set log.level: debug
but i can't find the output, /var/log/logstash/logstash.log is just empty

**Comment by mkristian** [comment]
@vilure `OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000faa00000, 75497472, 0) failed; error='Cannot allocate memory' (errno=12)`
looks odd

@jsvd @purbon can you give us a hint how to see the debug from bundler + jar-dependencies ? with this above memory issue it looks like something different going on here

**Comment by vilure** [comment]
I installed java from apt, kibana uses java and it feels ok for now..., top says i have 80% ram free

**Comment by sy43165** [comment]
I'm having this issue on Windows Server 2012 R2.  Is there a solution for Windows?

> D:\ELK\logstash-5.0.0>.\bin\logstash-plugin.bat install logstash-input-beats
> Validating logstash-input-beats
> Installing logstash-input-beats
> Error Bundler::InstallError, retrying 1/10
> An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
> Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.

**Comment by RohitMungi** [comment]
I am having the same issue as @sy43165 , When I try to install the required gem the following error is seen on windows: 
`
C:\logstash-5.0.0\bin>gem install logstash-core-event-java -v '5.0.0'
ERROR:  Could not find a valid gem 'logstash-core-event-java' (= 5.0.0), here is why:
          Found logstash-core-event-java (5.0.0), but was for platform java
ERROR:  Possible alternatives: logstash-codec-avro, logstash-output-jira, logstash-input-eventlog, logstash-event, logstash-codec-csv

C:\logstash-5.0.0\bin>
`
Dependencies ruby-maven and jar-dependencies are also installed. Is there a solution for this?

**Comment by mkristian** [comment]
@RohitMungi there errror says the gem is for platform java so it can not install this. I would conclude from this that you are using native ruby instead of jruby to install the gem. as jruby is picking platform java gems over platform ruby gems. could verify that you are indeed using jruby:
```
ruby --version
```
and/or
```
gem env
```

**Comment by RohitMungi** [comment]
@mkristian  Thanks for  pointing that out. I was using native version of ruby. I have now changed it to use jruby version and the gem seems to have installed. 

C:\logstash-5.0.0>jruby --version
jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.31-b07 on 1.8.0_31-b13 +jit [mswin32-x86_64]

C:\logstash-5.0.0>gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.8
  - RUBY VERSION: 2.3.1 (2016-11-09 patchlevel 0) [java]
  - INSTALLATION DIRECTORY: C:/jruby-9.1.6.0/lib/ruby/gems/shared
  - USER INSTALLATION DIRECTORY: C:/Users/Rohit Mungi/.gem/jruby/2.3.0
  - RUBY EXECUTABLE: C:/jruby-9.1.6.0/bin/jruby.exe
  - EXECUTABLE DIRECTORY: C:/jruby-9.1.6.0/bin
  - SPEC CACHE DIRECTORY: C:/Users/Rohit Mungi/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/jruby-9.1.6.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-java-1.8
  - GEM PATHS:
     - C:/jruby-9.1.6.0/lib/ruby/gems/shared
     - C:/Users/Rohit Mungi/.gem/jruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-rdoc --no-ri --env-shebang"
     - "update" => "--no-rdoc --no-ri --env-shebang"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\ProgramData\Oracle\Java\javapath
     - C:\Program Files (x86)\Intel\TXE Components\TCS\
     - C:\Program Files\Intel\TXE Components\TCS\
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
     - C:\Program Files\Hewlett-Packard\SimplePass\
     - C:\Program Files\Java\jdk1.8.0_31\\bin
     - C:\Program Files\Apache Software Foundation\apache-maven-3.1.1\bin
     - C:\Program Files (x86)\Skype\Phone\
     - c:\jruby-9.1.6.0\bin
     - c:\jruby-9.1.6.0\bin
C:\logstash-5.0.0>gem list logstash-core-event-java

*** LOCAL GEMS ***

logstash-core-event-java (5.0.0 java)


But I do get the same error when i try to install the plugin.

C:\logstash-5.0.0>bin\logstash-plugin.bat install logstash-input-beats
Validating logstash-input-beats
Installing logstash-input-beats
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.0.0'` succeeds before bundling.

**Comment by mkristian** [comment]
@RohitMungi I am not familiar with windows so if you could set the environment variable `JARS_DEBUG` to 'true' should produce some debug output (not sure though with plugin install of logstash). maybe there is also a way to turn on debug or verbose on the plugin.bat !

the other thing which is probably not the case but it there still a native ruby on the `PATH` ?

**Comment by RohitMungi** [comment]
@mkristian I think i found the issue here, The installation was unable to create a local maven repository while installing the required gems of the plugin. I changed the maven settings.xml to a different path and provided full access which installed the gem and the plugin.

Validating logstash-input-beats
Installing logstash-input-beats
Installation successful

Thanks for your inputs on this.

**Comment by mkristian** [comment]
@RohitMungi that is actually good news. jar-dependencies can check if the local maven repo exists and can be created at that location. thanks for reporting.

**Comment by r32rtb** [comment]
So I've been having this issue, we utilize Blue Coat proxies and the following file needs to be setup with the proxy settings and this issue was resolved for me.  Both remote and local plugin installs work on Ubuntu 16.04 with this setting.

Update:
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/ruby-maven-libs-3.3.9/maven-home/conf/settings.xml

and place your proxy settings in the proxies tag area...

**Comment by sandeepkanabar** [comment]
Thanks @r32rtb , that helped immensely
