### ISSUE TITLE
Test failure: 176 specs failed

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7159]
https://logstash-ci.elastic.co/job/elastic+logstash+master+dockerubuntu-periodic/2093/consoleFull

Wild. 176 specs failured in this build failure!

98 instances of this:

       The queue failed to obtain exclusive access, cause: Lock held by this virtual machine on lock path: /tmp/logstash/data/queue/main/.lock

% curl -s https://logstash-ci.elastic.co/job/elastic+logstash+master+dockerubuntu-periodic/2093/consoleFull | grep -
c '^ *The queue failed to obtain'
98

The others seem to be this:

     LogStash::Instrument::MetricStore::MetricNotFound:
       For path: config. Map keys: [:plugins, :reloads]

**Comment by original-brownbear** [comment]
@jordansissel urgh this is the RSpec equivalent of #7137 imo. We need to randomize the path we run from, otherwise it's very hard to figure out what caused the lock not to be released.

**Comment by andrewvc** [comment]
I'm +1 on randomizing the path

**Comment by colinsurprenant** [comment]
I understand that having failures cascade because a lock was not properly released is not ideal but we have to keep in mind that it may also indicate that the queue was not properly closed in a tested code path. 

So while thinking about a solution for this, if it is judged this is an important enough problem to fix and a priority, let's try not to come up with something that may simply *hide* that particular problem. This is more specific for the Ruby specs where more *complex* tests are done, on the pipeline reload scenarios for example (complex in terms of what is happening behind the scene as opposed to *simple* queue unit tests).

So, if/when working on this, please bare this in mind.

**Comment by andrewvc** [comment]
@colinsurprenant I agree that we should not hide the problem. What I'm trying to say is that we should randomize the path to get all the current tests to pass and also make a new test that fails consistently with whatever the issue here is.

**Comment by andrewvc** [comment]
These would obviously be merged in one commit/PR

**Comment by colinsurprenant** [comment]
@andrewvc but what is the cause of the failure? is it because the path is not randomized or is it because one test creates a failure cascade? In other words, does fixing that one test solves  the failure cascade? 

What I am trying to say is that I am not sure that simply randomizing is the right action here because it may hide another problem. As much as a failure cascade is hard to deal with, it is *probably* indicative of another problem which should be solved.

**Comment by original-brownbear** [comment]
@andrewvc @colinsurprenant guys I think this can be resolved without resorting to brute-force running the tests against the same dir and then doing forensics, while still having the same coverage.

Why not just run some verification that `.lock` is gone for each test this problem applies to in the `after` block?

The cause is clear, if you guys look at the way Ruby uses the `Queue`, there is no finalizerish thing running, if your code errors out at the wrong place with an open Queue -> no unlock enforced => this should be fixed and get a separate clear cut integration test.

**Comment by colinsurprenant** [comment]
Ok then, which are the «tests this problem applies to»??

It seems we are kind of debating over thin-air. Here's what I'd like to see:
1- what was the exact cause of the failures in this report and was it fixed?
2- is that a recurring issue?
3- what specifically are we suggesting to fix?

**Comment by original-brownbear** [comment]
@colinsurprenant 

Damn you're raising an annoying point (though you couldn't be more correct :D)

I think the initial failure was:

> 
> 1- what was the exact cause of the failures in this report and was it fixed?
> 2- is that a recurring issue?


```sh
 LogStash::Instrument::MetricStore::MetricNotFound:
   For path: config. Map keys: [:plugins, :reloads]
```

This should probably be investigated and the path discussion moved to the next issue.

>  «tests this problem applies to»

Now that you ask ... damn, pretty much all of them it looks like. I guess this is a strong argument for randomized paths since it completely precludes parallel test exec at the moment.

> 3- what specifically are we suggesting to fix?

Let's fix this issue and I'll add a new one for safely handling the Queue on the Ruby end? :)

**Comment by colinsurprenant** [comment]
@original-brownbear Ok let's do that. 

Parallel test execution is a good point but there might also be many other considerations to achieve this so unless this becomes a thing (aiming at parallelizing our tests), *and I am fine if it does*, it is not in itself an argument to refactor the Ruby specs. 

What I want to avoid here, is justify a refactor because it feels right, and it might be, but for a problem that creates occasional inconveniences (failure cascades) but which unveils another problem which does need to be fixed. I feel that this is not well understood or underestimated in this discussion. Bare in mind that most if not all specs that includes firing a pipeline will incidentally create a queue and that normally, a test should not prevent another test from running (excluding the parallel testing case) and if it does then this **usually** point to another problem which might have been simply hidden if a *blind* path randomization strategy was put in place. So I am not saying we should drop that idea altogether but I want to make sure it is understood and taken into account when proposing a fix.

**Comment by suyograo** [comment]
Closing since these test failures don't occur anymore
