### ISSUE TITLE
Too many file descriptors used by UDP and TCP plugins (IO.select())

### ISSUE THREAD

**Issue by micoq** [elastic/logstash#7401]
Currently, the udp and tcp input plugins (logstash-input-udp and logstash-input-tcp) cannot accept more than ~1024 clients because the use of `IO::Select` in these plugins (it's not an "ulimit" problem, it's a hard coded limitation of the `select()` syscall).

It can be an issue if you want to use Logstash as a central collector for Syslog events (e.g. to replace Rsyslog).

If the number of clients reach the limit, the plugin's thread crash (not Logstash) and cannot recover (despite of the message `A plugin had an unrecoverable error. Will restart this plugin.`) with the following message (for TCP):
```
[ERROR][logstash.inputs.tcp      ] An error occurred. Closing connection {:client=>"10.0.0.1:50748", :exception=>#<IOError: Too many open files>, :backtrace=>["org/jruby/RubyIO.java:3019:in `sysread'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:240:in `read'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:164:in `handle_socket'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:153:in `server_connection_thread'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:151:in `server_connection_thread'"]}
```
or this message (for UDP):
```
[WARN ][logstash.inputs.udp      ] UDP listener died {:exception=>#<IOError: closed stream>, :backtrace=>["org/jruby/RubyIO.java:3705:in `select'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:93:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:56:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:425:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:419:in `start_input'"]}
```
Therefore, the listening socket is closed.

Is there a better solution to avoid the `IO.select()` call (like `poll()` or maybe `nio` in the java layer) to handle more clients ?

**Comment by micoq** [comment]
Just some additional informations : The `select()` call can't handle file descriptors greater than 1024 so if a plugin which uses `select()` runs in a Logstash instance which open many file descriptors, this plugin may crash even if it doesn't use itself a few file descriptors.
In my case, I use both TCP and UDP plugins on the same instance. If the TCP plugin eats many file descriptors, the UDP plugin could crash because its single socket has a file descriptor identifier above the 1024 limit and the `IO.select([@udp], [], [], 0.5)` fails.

Actually, this could happen on any plugin which uses `select()`.

**Comment by original-brownbear** [comment]
I think moving to `java.nio` I/O for this stuff make a lot of sense to avoid the limits of `select`.
At least on Linux the combination of non-blocking `SocketChannel`s and  `Selector` gives us a nice `epoll` implementation.
@suyograo what do you think, maybe we could do this for the tcp input ( https://github.com/logstash-plugins/logstash-input-tcp ) as a first step (we wanted to optimize it anyhow)? :)

**Comment by micoq** [comment]
Actually, the `IO.select()` implementation seems to use nio which uses `Selector` and finally `poll` or `epoll`. With `strace` on the Logstash process, I see many `epoll_*` calls. I'll try to make further investigation (it's not ulimit since I have 65536 descriptors allowed per process).

**Comment by suyograo** [comment]
@original-brownbear @micoq +1 on moving to Java IO for TCP and UDP. We initially wanted to move to Netty, but we can go directly to Java standard libs.

**Comment by micoq** [comment]
@original-brownbear @suyograo  `IO.Select()` in Jruby effectively uses epoll and not select. Sorry for my mistake !
However, there is a strange behavior when a TCP connection is accepted: each connection create a thread and a eventpoll process:

```
$ lsof -p <pid of logstash>
...
java    11278 mic   82u     IPv6             205555      0t0     TCP localhost:7777->localhost:39932 (ESTABLISHED)
java    11278 mic   83r     FIFO               0,10      0t0  212116 pipe
java    11278 mic   84w     FIFO               0,10      0t0  212116 pipe
java    11278 mic   85u  a_inode               0,11        0    9538 [eventpoll]
...

$ top -b -n 1 -H -p <pid of logstash>
...
11363 mic    20   0 5888120 396160  18748 S  0,0  3,2   0:00.01 [main]<tcp
...
```
So, a single client consumes 4 descriptors and 1 thread. In my initial post, I made a mistake: the descriptors limits were 4096, not 65536 that's why I run out of descriptors.

If we look at the source code of JRuby, the `IO.select()` call will retrieve a NIO `Selector` from a selector pool (https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/util/io/SelectorPool.java). After the use of the selector, it will not be closed but simply returned to the pool and can be reused by a further `IO.select()` call. But why is there only a single socket per selector ?
I didn't find a way to limit the pool size: You can have 10, 100, 1000 selectors ! (and threads)

**Comment by micoq** [comment]
Well, it's a bit tricky:
When `IO.Select()` is called, JRuby create a new Selector whenever you called `IO.Select()` before or not (the selector pool isn't used). On Linux, this will constantly create and destroy a file descriptor with `epoll_create`. It could explain why the UDP input plugin crash when there isn't any file descriptor available.

The TCP input plugin doesn't use `IO.Select()` but it uses selectors (and epoll) inside the blocking call `socket.sysread()`. Unlike to `IO.Select()`, the selector pool is used so only one selector is created but for each thread ! Actually, there is one selector pool per thread and the plugin creates one thread for each client. That's why there's so much selectors/file descriptors.

I made a quick benchmark with a modified TCP plugin to use a single thread (with `IO.Select()`), it can handle thousands of clients and a total of 20000 ev/s (at 100% CPU). A better solution could be a configurable thread pool to distribute the connections.
Finally, a pure java implementation would be better to avoid the creation/destruction of the selector in `IO.select()`.

**Comment by original-brownbear** [comment]
@micoq good news here, sorry missed updating this thread, but we released a new version (`4.2.2`) of the TCP input https://rubygems.org/gems/logstash-input-tcp that uses a Netty based, non-blocking and single-threaded I/O loop (combined with multi-threaded decoding of events) for the non-SSL use case of that plugin. Feel free to give that a try, it should handle the many connections use case just fine now without creating thousands of threads.

**Comment by micoq** [comment]
@original-brownbear nice job !
I just installed this new version on a setup with ~500 clients and it works well. I didn't performed a benchmark but the number of threads have been reduced like the memory consumed by thread stacks (200 threads for the whole instance with 500 clients).
However, I still see many `[eventpoll]` and `pipe` descriptors with `lsof. Is it expected ? (~500 eventpoll for 500 connections, I didn't try to change the number of clients yet)
```
....
java    383 logstash 1613u  a_inode                0,9         0     9542 [eventpoll]
java    383 logstash 1614r     FIFO                0,8       0t0 82208229 pipe
java    383 logstash 1615w     FIFO                0,8       0t0 82208229 pipe
java    383 logstash 1616u  a_inode                0,9         0     9542 [eventpoll]
java    383 logstash 1617r     FIFO                0,8       0t0 82208230 pipe
java    383 logstash 1618w     FIFO                0,8       0t0 82208230 pipe
java    383 logstash 1619u  a_inode                0,9         0     9542 [eventpoll]
java    383 logstash 1620r     FIFO                0,8       0t0 82208231 pipe
java    383 logstash 1621w     FIFO                0,8       0t0 82208231 pipe
java    383 logstash 1622u  a_inode                0,9         0     9542 [eventpoll]
java    383 logstash 1623r     FIFO                0,8       0t0 82208232 pipe
java    383 logstash 1624w     FIFO                0,8       0t0 82208232 pipe
java    383 logstash 1625u  a_inode                0,9         0     9542 [eventpoll]
java    383 logstash 1626r     FIFO                0,8       0t0 82208233 pipe
java    383 logstash 1627w     FIFO                0,8       0t0 82208233 pipe
...
```

**Comment by original-brownbear** [comment]
@micoq I think the anonymous inodes are expected. Netty uses `epoll` and this is standard epoll behavior as far as I know :)

**Comment by micoq** [comment]
@original-brownbear I understood why: the [worker event loop](https://github.com/logstash-plugins/logstash-input-tcp/blob/master/src/main/java/org/logstash/tcp/InputLoop.java#L43) allocates by default a number of 2*CPUs threads (and selectors/epoll descriptors). In our machines, we have 40 CPU cores so 80 worker threads !

However, we can change the default number of threads with the java system property `io.netty.eventLoopThreads`. In the netty source code, there is something like this:
```
DEFAULT_EVENT_LOOP_THREADS = Math.max(1, SystemPropertyUtil.getInt("io.netty.eventLoopThreads", Runtime.getRuntime().availableProcessors() * 2));
```
In this case, it's not a big problem since the number of threads/selectors doesn't increase anymore with the number of clients: the _boss_ loop take care of `accept()` and distribute the newly-opened connection to a worker loop which uses a selector/epoll descriptor (one per thread).

I didn't know Netty. It could be a very nice base to unify the network based plugins around NIO and to have a global input thread pool to maximize the CPU utilization and keeping a minimal overhead.

**Comment by original-brownbear** [comment]
Closing here for now since there isn't anything actionable left :)

**Comment by abdalians** [comment]
Thank your for implementing this fix.
