### ISSUE TITLE
Accessing Metrics Endpoint during Startup Returns HTTP Status 500 

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#8004]
If I keep refreshing my browser pointed at the metrics page during LS startup I get this error in the logs:

```sh
➜  logstash git:(master) bin/logstash -b 128 -w 1 -e 'input { generator{}} output {stdout {codec => "dots"}}' 
WARNING: Default JAVA_OPTS will be overridden by the JAVA_OPTS defined in the environment. Environment JAVA_OPTS are -Xms4g -Xmx4g -Djava.net.preferIPv4Stack=true
Sending Logstash's logs to /Users/brownbear/src/logstash/logs which is now configured via log4j2.properties
[2017-08-16T17:19:10,018][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/Users/brownbear/src/logstash/modules/fb_apache/configuration"}
[2017-08-16T17:19:10,036][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/Users/brownbear/src/logstash/modules/netflow/configuration"}
[2017-08-16T17:19:10,222][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2017-08-16T17:19:11,080][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-08-16T17:19:11,925][ERROR][logstash.agent           ] Internal API server error {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats/", :query_string=>"pretty", :http_version=>"HTTP/1.1", :http_accept=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", :error=>"Unexpected Internal Error", :class=>"LogStash::Instrument::MetricStore::MetricNotFound", :message=>"For path: events. Map keys: [:reloads]", :backtrace=>["/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:225:in `block in get_recursively'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:235:in `block in get_recursively'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:95:in `block in get'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:94:in `get'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:108:in `get_shallow'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:157:in `block in extract_metrics'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyEnumerable.java:936:in `inject'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:133:in `extract_metrics'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/service.rb:30:in `extract_metrics'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/commands/base.rb:22:in `extract_metrics'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/commands/stats.rb:42:in `events'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:35:in `events_payload'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:21:in `block in GET /?:filter?'", "org/jruby/RubyMethod.java:111:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/nulllogger.rb:9:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/head.rb:13:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:66:in `block in call'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:50:in `call'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:57:in `call'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:31:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/builder.rb:153:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:557:in `handle_request'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:404:in `process_client'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:270:in `block in run'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:106:in `block in spawn_thread'"]}
[2017-08-16T17:19:11,926][ERROR][logstash.agent           ] Internal API server error {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats/", :query_string=>"pretty", :http_version=>"HTTP/1.1", :http_accept=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", :error=>"Unexpected Internal Error", :class=>"LogStash::Instrument::MetricStore::MetricNotFound", :message=>"For path: events. Map keys: [:reloads]", :backtrace=>["/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:225:in `block in get_recursively'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:235:in `block in get_recursively'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:95:in `block in get'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:94:in `get'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:108:in `get_shallow'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:157:in `block in extract_metrics'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyEnumerable.java:936:in `inject'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:133:in `extract_metrics'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/service.rb:30:in `extract_metrics'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/commands/base.rb:22:in `extract_metrics'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/commands/stats.rb:42:in `events'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:35:in `events_payload'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:21:in `block in GET /?:filter?'", "org/jruby/RubyMethod.java:111:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/nulllogger.rb:9:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/head.rb:13:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:66:in `block in call'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:50:in `call'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:57:in `call'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:31:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/builder.rb:153:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:557:in `handle_request'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:404:in `process_client'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:270:in `block in run'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:106:in `block in spawn_thread'"]}
[2017-08-16T17:19:11,926][ERROR][logstash.agent           ] Internal API server error {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats/", :query_string=>"pretty", :http_version=>"HTTP/1.1", :http_accept=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", :error=>"Unexpected Internal Error", :class=>"LogStash::Instrument::MetricStore::MetricNotFound", :message=>"For path: events. Map keys: [:reloads]", :backtrace=>["/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:225:in `block in get_recursively'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:235:in `block in get_recursively'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:95:in `block in get'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:94:in `get'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:108:in `get_shallow'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:157:in `block in extract_metrics'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyEnumerable.java:936:in `inject'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:133:in `extract_metrics'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/service.rb:30:in `extract_metrics'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/commands/base.rb:22:in `extract_metrics'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/commands/stats.rb:42:in `events'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:35:in `events_payload'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:21:in `block in NodeStats'", "org/jruby/RubyMethod.java:111:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/nulllogger.rb:9:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/head.rb:13:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:66:in `block in call'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:50:in `call'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:57:in `call'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:31:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/builder.rb:153:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:557:in `handle_request'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:404:in `process_client'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:270:in `block in run'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:106:in `block in spawn_thread'"]}
[2017-08-16T17:19:11,926][ERROR][logstash.agent           ] Internal API server error {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats/", :query_string=>"pretty", :http_version=>"HTTP/1.1", :http_accept=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", :error=>"Unexpected Internal Error", :class=>"LogStash::Instrument::MetricStore::MetricNotFound", :message=>"For path: events. Map keys: [:reloads]", :backtrace=>["/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:225:in `block in get_recursively'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:235:in `block in get_recursively'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:95:in `block in get'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:94:in `get'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:108:in `get_shallow'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:157:in `block in extract_metrics'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyEnumerable.java:936:in `inject'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:133:in `extract_metrics'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/service.rb:30:in `extract_metrics'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/commands/base.rb:22:in `extract_metrics'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/commands/stats.rb:42:in `events'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:35:in `events_payload'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:21:in `block in NodeStats'", "org/jruby/RubyMethod.java:111:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/nulllogger.rb:9:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/head.rb:13:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:66:in `block in call'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:50:in `call'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:57:in `call'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:31:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/builder.rb:153:in `call'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:557:in `handle_request'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:404:in `process_client'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:270:in `block in run'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:106:in `block in spawn_thread'"]}
[2017-08-16T17:19:11,975][ERROR][logstash.agent           ] API HTTP Request {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats/", :query_string=>"pretty", :http_version=>"HTTP/1.1", :http_accept=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"}
[2017-08-16T17:19:11,976][ERROR][logstash.agent           ] API HTTP Request {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats/", :query_string=>"pretty", :http_version=>"HTTP/1.1", :http_accept=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"}
[2017-08-16T17:19:11,976][ERROR][logstash.agent           ] API HTTP Request {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats/", :query_string=>"pretty", :http_version=>"HTTP/1.1", :http_accept=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"}
[2017-08-16T17:19:11,976][ERROR][logstash.agent           ] API HTTP Request {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats/", :query_string=>"pretty", :http_version=>"HTTP/1.1", :http_accept=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"}
[2017-08-16T17:19:13,003][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>1, "pipeline.batch.size"=>128, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>128, :thread=>"#<Thread:0x3af3ce06 run>"}
[2017-08-16T17:19:13,024][INFO ][logstash.pipeline        ] Pipeline started {"pipeline.id"=>"main"}
[2017-08-16T17:19:13,109][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}
```

and this as the output in the browser:

```
{"status":500,"request_method":"GET","path_info":"/_node/stats/","query_string":"pretty","http_version":"HTTP/1.1","http_accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","error":"Unexpected Internal Error","class":"LogStash::Instrument::MetricStore::MetricNotFound","message":"For path: events. Map keys: [:reloads]","backtrace":["/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:225:in `block in get_recursively'","org/jruby/RubyArray.java:1734:in `each'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:235:in `block in get_recursively'","org/jruby/RubyArray.java:1734:in `each'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:95:in `block in get'","org/jruby/ext/thread/Mutex.java:148:in `synchronize'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:94:in `get'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:108:in `get_shallow'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:157:in `block in extract_metrics'","org/jruby/RubyArray.java:1734:in `each'","org/jruby/RubyEnumerable.java:936:in `inject'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:133:in `extract_metrics'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/service.rb:30:in `extract_metrics'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/commands/base.rb:22:in `extract_metrics'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/commands/stats.rb:42:in `events'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:35:in `events_payload'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:21:in `block in NodeStats'","org/jruby/RubyMethod.java:111:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'","org/jruby/RubyKernel.java:1120:in `catch'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'","org/jruby/RubyArray.java:1734:in `each'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'","org/jruby/RubyKernel.java:1120:in `catch'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'","org/jruby/RubyKernel.java:1120:in `catch'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/nulllogger.rb:9:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/head.rb:13:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:66:in `block in call'","org/jruby/RubyArray.java:1734:in `each'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:50:in `call'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:57:in `call'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:31:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/builder.rb:153:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:557:in `handle_request'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:404:in `process_client'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:270:in `block in run'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:106:in `block in spawn_thread'"]}
```

startup proceeds just fine afterwards though, so it's more of a cosmetic issue imo.

**Comment by colinsurprenant** [comment]
thinking out loud: could we rely on the `Pipeline#ready?`  (or something similar) method in the metrics api to return a better *not ready* response or just not accept requests before it is ready?

**Comment by simmel** [comment]
This is still an issue. Do you need more debug log or anything else to fix this?

For us it takes ~30s between the API is up and until all of the config has been parsed.

**Comment by original-brownbear** [comment]
@simmel thanks we got this tracked down already :) For the record, imo #8509 is a fine patch here ...

**Comment by simmel** [comment]
Ouch. It's not being pulled in until 7.0? ='(

**Comment by original-brownbear** [comment]
@simmel finally fixed via https://github.com/elastic/logstash/pull/9398 (went into`6.x` and `master`).

**Comment by simmel** [comment]
Sweet @original-brownbear, thanks for the update!

**Comment by lbesuchet** [comment]
The issue seems to happen again since v12.0

**Comment by cstegm** [comment]
I have that issue when central pipeline mangement is configured, but no pipeline is deployed to logstash.

**Comment by AlphaRaven** [comment]
Still seeing this issue in 7.17.1 as it's mentioned in #12919 and also (my duplicate post) #13313
